name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Hello world action
    env: # Or as an environment variable
      apiURL: ${{ secrets.apiURL }}
