name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#       with:
#         args: --acl public-read --follow-symlinks --delete
#       env:
#         apiURL: ${{ secrets.apiURL }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies (prod)
        run: yarn install --frozen-lockfile --production
        
        env:
          CI: true
          apiURL: ${{ secrets.apiURL }}

